/**
 * TypeScript 类型参考（不声明，避免与 @logseq/libs 冲突）
 * @logseq/libs 已提供全局 logseq 对象的完整类型
 * 此文件仅作参考文档
 */

// @logseq/libs 提供的全局对象 logseq 类型：
// - logseq.Editor: IEditorProxy (registerSlashCommand, insertBlock, updateBlock, removeBlock, getBlock, getPage, createPage, createJournalPage, getCurrentPage, getPageBlocksTree, getPageLinkedReferences, getAllPages, getPageProperties, ...
// - logseq.App: IAppProxy (registerUIItem, getInfo, getUserConfigs, ...
// - logseq.DB: IDBProxy (q, customQuery, datascriptQuery, onChanged, ...
// - logseq.UI: IUIProxy (showMsg, ...
// - logseq.provideModel, provideStyle, showMainUI, hideMainUI, setMainUIInlineStyle, useSettingsSchema, ...

export {};
